/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * API health check
         * @description Returns the API status and uptime
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description API is healthy */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all available products
         * @description Returns all available products
         */
        get: {
            parameters: {
                query?: {
                    /** @description Opaque pagination cursor. */
                    cursor?: string;
                    limit?: number;
                    /** @description Full-text search query. */
                    q?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A list of available products */
                200: {
                    headers: {
                        /** @description Present if there is another page. */
                        "X-Next-Cursor"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProductsResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create a new product
         * @description Creates a new product
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ProductCreate"];
                };
            };
            responses: {
                /** @description Product created successfully */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Product"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{productId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: string;
            };
            cookie?: never;
        };
        /** Get product */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    productId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The product */
                200: {
                    headers: {
                        ETag?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Product"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /** @example ok */
            status: string;
            /**
             * @description Time in seconds since the API started
             * @example 123.456
             */
            uptime: number;
        };
        Product: {
            /** Format: uuid */
            id: string;
            name: string;
            artist: string;
            images?: components["schemas"]["ImageVariantSet"][];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        ProductsResponse: {
            products: components["schemas"]["Product"][];
        };
        ProductCreate: {
            name: string;
            artist: string;
            /** @description Object storage key for a previously uploaded original */
            imageKey?: string | null;
        };
        ImageVariantSet: {
            original: components["schemas"]["ImageRef"];
            thumb?: components["schemas"]["ImageRef"];
            medium?: components["schemas"]["ImageRef"];
        };
        ImageRef: {
            /** Format: uri */
            url: string;
            width: number;
            height: number;
            /** @enum {string} */
            format: "jpeg" | "png" | "webp" | "avif";
        };
        Error: {
            /** @example An error occurred */
            title: string;
            /** @example Detailed error message */
            message?: string;
            /** @example 500 */
            code?: number;
        };
    };
    responses: {
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Version conflict (ETag mismatch) */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        ProductId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
